### ISSUE TITLE
very high memory consumption compared to provider-terraform

### ISSUE THREAD

**Issue by ztzxt** [upbound/provider-opentofu#55]
Hi,

We have started using `provider-opentofu` as a replacement for deprecated provider-terraform.  Even though we have the same amount of `Workspace` resources, opentofu provider is using at least 10x memory on average compared to terraform provider. 

terraform provider memory consumption: (around 800 megabyte)

<img width="1895" alt="Image" src="https://github.com/user-attachments/assets/db84e09d-7add-4f79-9c71-e8c146e6b479" />

opentofu provider memory consumption: (around 10 gigabyte)

<img width="1894" alt="Image" src="https://github.com/user-attachments/assets/9db9a465-bf2d-4d42-adf5-d47675c2479f" />

for both, we are installing them via helm chart like this:

```yaml
provider:
  packages:
    - xpkg.upbound.io/upbound/provider-terraform:v0
    - xpkg.upbound.io/upbound/provider-opentofu:v0

```
