### ISSUE TITLE
unexpected CannotConnectToProvider events

### ISSUE THREAD

**Issue by ztzxt** [upbound/provider-opentofu#56]
Opentofu Workspace resources start emitting `CannotConnectToProvider`, and their synced status becomes unhealthy with the following data:

```
status:
  conditions:
    - lastTransitionTime: '2025-04-13T16:57:12Z'
      message: >
        connect failed: cannot get remote tofu module: error downloading
        'https://github.com/justtrackio/terraform-aws-ecs-gosoline-monitoring?ref=v2.7.2':
        /usr/bin/git exited with 255: error: cannot fork() for remote-https:
        Resource temporarily unavailable
      reason: ReconcileError
      status: 'False'
      type: Synced
```

When we get these errors, the module referenced is still available, and it can be pulled locally via terraform/opentofu. I think similar behavior existed in `provider-terraform` as well (https://github.com/upbound/provider-terraform/issues/319), but I cannot point out where it comes from.

Restarting the provider forces them to resync, and workspaces become healthy for some time, but eventually, the same error message pops back again.

**Comment by ztzxt** [comment]
I've exec'd into the provider pod, and it seems like git processes are not killed properly, causing pod to hit max process count. 

```shell
upbound-provider-opentofu-7eb040fab77b-b78f57bcc-qp2rf:/$ ps | wc -l
502

upbound-provider-opentofu-7eb040fab77b-b78f57bcc-qp2rf:/$ ps | grep git | wc -l
499

upbound-provider-opentofu-7eb040fab77b-b78f57bcc-qp2rf:/$ps-eo ppid,pid.comm | grep git | head
1 46 git
1 52 git
1 6 git
1 638 git
1 644 git
1 653 git
1 1232 git
1 1238 git
1 1247 git
1 1830 git
```

for every other spawned process, they are properly killed when they are done

**Comment by applike-ss** [comment]
We've seen that switching from git to https for our modules has shown no more zombie like processes here.

Something in the provider seems to be off making it keep some git processes open.
Maybe some invalid input specified or git asking back for any input?

**Comment by jeremydescamps** [comment]
On my side I always have configured like this:

```yaml
forProvider:
  enableTofuCLILogging: true
  source: "Remote"
  module: "git::https://gitlab.company.org/module-tf.git?ref=v0.1.0"
```

But we still get the "Cannot fork" error.

Rollout restart the `opentofu` deployment fixed it but so far we don't have any other hint.
